### ISSUE TITLE
reghdfe_store_alphas is unrecognized

### ISSUE THREAD

**Issue by angelaywu** [sergiocorreia/ivreghdfe#17]
When I run the sample code in Readme with option to save fixed effect, there's an error message saying the command reghdfe_store_alphas is unrecognized. 

I've downloaded the latest version from Github, and the codes are below. Thank you!

```
. sysuse auto, clear
(1978 Automobile Data)

. ivreghdfe price weight, absorb(trunk, save)
(dropped 5 singleton observations)
(MWFE estimator converged in 1 iterations)
command reghdfe_store_alphas is unrecognized
r(199)
```
```
. which reghdfe
*! version 5.7.1 20mar2019

. which ivreghdfe
*! ivreghdfe 1.0.0  07jul2018
*! this just adds absorb() to this code:
*! ivreg2 4.1.10  9Feb2016
*! authors cfb & mes
*! see end of file for version comments
```

**Comment by psvatsa** [comment]
resolved?

**Comment by yfeyman** [comment]
Has there been an update? This error still occurs. 

`
. which reghdfe
c:\ado\plus\r\reghdfe.ado
*! version 5.7.1 20mar2019

. which ivreghdfe
c:\ado\plus\i\ivreghdfe.ado
*! ivreghdfe 1.0.0  07jul2018
*! this just adds absorb() to this code:
*! ivreg2 4.1.10  9Feb2016
*! authors cfb & mes
*! see end of file for version comments

`

**Comment by sergiocorreia** [comment]
Can you try with the commit I just added? It works on my side.

**Comment by yfeyman** [comment]
Ah, sorry. Didn't see that there was another branch. I tried reinstalling from there and it looks like it works now!

**Comment by pxv148** [comment]
I am sorry what must I do to get it working? sorry for the noob questions... but someone has gotta ask them ? :(

**Comment by sergiocorreia** [comment]
I just added a new version to github. So uninstalling and reinstalling from there should so the trick.

**Comment by yfeyman** [comment]
@pxv148 run the following in stata:

cap ado uninstall ivreghdfe
net install ivreghdfe, from(https://raw.githubusercontent.com/sergiocorreia/ivreghdfe/mead/src/)

**Comment by angelaywu** [comment]
Thank you!
